package app.revanced.extension.gamehub.componentstore;

import android.util.Log;

import java.util.HashMap;
import java.util.Map;

/**
 * Mali GPU optimization layer - provides environment variables and runtime
 * tuning for Mali-G710 and other Mali GPUs when running Wine/DXVK/VKD3D.
 * 
 * Based on user memory notes about Mali-G710 (Panfrost driver, AFBC texture
 * compression issues, Mesa tuning flags) and community best practices.
 */
public class MaliOptimizer {
    private static final String TAG = "BH-MaliOptimizer";
    
    /**
     * Get Mali-specific environment variables for Wine/Proton processes.
     * These should be applied when launching games on Mali GPUs.
     */
    public static Map<String, String> getMaliEnvVars() {
        Map<String, String> env = new HashMap<>();
        
        if (!DeviceInfo.getGpuFamily().equals("mali")) {
            return env; // Not Mali, return empty
        }
        
        Log.i(TAG, "Applying Mali GPU optimizations for " + DeviceInfo.getGpuModel());
        
        // Mesa tuning flags
        // MESA_NO_ERROR: Skip GL error checking for performance (use carefully)
        env.put("MESA_NO_ERROR", "1");
        
        // Shader cache to avoid recompilation
        env.put("MESA_GLSL_CACHE_DISABLE", "false");
        env.put("MESA_SHADER_CACHE_DISABLE", "false");
        
        // Mali-G710 specific: AFBC (ARM Frame Buffer Compression) workaround
        // User memory mentions AFBC corruption issues
        if (DeviceInfo.isMaliG710()) {
            Log.i(TAG, "Mali-G710 detected - applying AFBC workarounds");
            
            // Disable AFBC if corruption occurs (user can toggle)
            // Note: This may reduce performance but fixes texture corruption
            // env.put("PAN_MESA_DEBUG", "noafbc");
            
            // Alternative: Use sync mode for debugging
            env.put("PAN_MESA_DEBUG", "sync");
            
            // Force linear tiling instead of AFBC (compatibility mode)
            env.put("PANFROST_NO_AFBC", "1");
        }
        
        // General Panfrost optimizations
        env.put("PAN_MESA_DEBUG", "trace,sync"); // Tracing + sync for stability
        
        // Vulkan optimizations for Mali
        env.put("MESA_VK_WSI_PRESENT_MODE", "mailbox"); // Reduce latency
        env.put("RADV_PERFTEST", "nggc"); // Enable NGG culling (if applicable)
        
        // Thread optimization - Mali benefits from more worker threads
        env.put("MESA_GLTHREAD", "true");
        env.put("mesa_glthread", "true");
        
        // Disable features that cause issues on Mali
        env.put("MESA_EXTENSION_OVERRIDE", "-GL_ARB_buffer_storage");
        
        // Vsync control
        env.put("vblank_mode", "0"); // Disable vsync for max FPS
        
        // Shader compiler optimizations
        env.put("NIR_VALIDATE", "0"); // Skip validation for speed
        
        return env;
    }
    
    /**
     * Get DXVK-specific config overrides for Mali GPUs.
     * These should be written to dxvk.conf in the Wine prefix.
     */
    public static String getDxvkConfigForMali() {
        if (!DeviceInfo.getGpuFamily().equals("mali")) {
            return "";
        }
        
        StringBuilder config = new StringBuilder();
        config.append("# DXVK Mali GPU Optimizations (Generated by BannerHub)\n");
        config.append("# These settings optimize DXVK for ARM Mali GPUs\n\n");
        
        // Memory allocation strategy
        config.append("# Memory management\n");
        config.append("dxvk.maxDeviceMemory = 2048\n"); // Limit to 2GB
        config.append("dxvk.maxSharedMemory = 512\n");
        
        // Graphics pipeline options
        config.append("\n# Pipeline optimizations\n");
        config.append("dxgi.maxFrameLatency = 1\n"); // Reduce latency
        config.append("dxgi.syncInterval = 0\n"); // Disable vsync
        
        // Shader compilation
        config.append("\n# Shader compilation\n");
        config.append("dxvk.useAsync = true\n"); // Async shader compilation
        config.append("dxvk.numCompilerThreads = 4\n");
        
        // Mali-G710 specific
        if (DeviceInfo.isMaliG710()) {
            config.append("\n# Mali-G710 specific\n");
            config.append("# Disable features known to cause issues\n");
            config.append("d3d11.relaxedBarriers = true\n");
            config.append("dxvk.enableGraphicsPipelineLibrary = false\n");
        }
        
        return config.toString();
    }
    
    /**
     * Get VKD3D-specific config for Mali GPUs.
     */
    public static String getVkd3dConfigForMali() {
        if (!DeviceInfo.getGpuFamily().equals("mali")) {
            return "";
        }
        
        StringBuilder config = new StringBuilder();
        config.append("# VKD3D Mali GPU Configuration\n\n");
        
        // Conservative settings for compatibility
        config.append("VKD3D_CONFIG=dxr11,dxr\n");
        config.append("VKD3D_FEATURE_LEVEL=12_0\n");
        
        // Mali-specific
        if (DeviceInfo.isMaliG710()) {
            config.append("# Mali-G710: Use conservative memory allocation\n");
            config.append("VKD3D_VULKAN_DEVICE=0\n");
        }
        
        return config.toString();
    }
    
    /**
     * Get recommended Wine prefix setup commands for Mali.
     */
    public static String[] getWinePrefixSetupCommands() {
        if (!DeviceInfo.getGpuFamily().equals("mali")) {
            return new String[0];
        }
        
        return new String[] {
            "# Mali GPU Wine Prefix Setup",
            "# Run these in the Wine prefix directory",
            "",
            "# Create DXVK config",
            "echo '" + getDxvkConfigForMali() + "' > dxvk.conf",
            "",
            "# Disable problematic features",
            "winetricks videomemorysize=2048",
            "",
            "# Registry tweaks for Mali compatibility",
            "wine reg add 'HKEY_CURRENT_USER\\Software\\Wine\\Direct3D' /v MaxVersionGL /t REG_DWORD /d 0x30002 /f",
            "wine reg add 'HKEY_CURRENT_USER\\Software\\Wine\\Direct3D' /v UseGLSL /t REG_SZ /d enabled /f"
        };
    }
    
    /**
     * Check if Mali optimizations should be applied.
     */
    public static boolean shouldApplyMaliOptimizations() {
        String gpu = DeviceInfo.getGpuFamily();
        return gpu.equals("mali");
    }
    
    /**
     * Get human-readable optimization summary for display.
     */
    public static String getOptimizationSummary() {
        if (!shouldApplyMaliOptimizations()) {
            return "No Mali-specific optimizations needed for " + DeviceInfo.getGpuModel();
        }
        
        StringBuilder summary = new StringBuilder();
        summary.append("Mali GPU Optimizations Active\n\n");
        summary.append("GPU: ").append(DeviceInfo.getGpuModel()).append("\n");
        summary.append("Architecture: ").append(DeviceInfo.getArchitecture()).append("\n\n");
        
        summary.append("Applied optimizations:\n");
        summary.append("• Mesa shader caching enabled\n");
        summary.append("• Multi-threaded GL rendering\n");
        summary.append("• Reduced frame latency\n");
        
        if (DeviceInfo.isMaliG710()) {
            summary.append("• Mali-G710 AFBC workarounds\n");
            summary.append("• Linear tiling fallback\n");
        }
        
        summary.append("\nNote: These settings optimize for compatibility.\n");
        summary.append("Adjust dxvk.conf and environment variables for your specific games.");
        
        return summary.toString();
    }
    
    /**
     * Apply Mali optimizations to a process environment map.
     * Call this before launching Wine/game processes.
     */
    public static void applyToProcessEnvironment(Map<String, String> processEnv) {
        if (!shouldApplyMaliOptimizations()) {
            return;
        }
        
        Map<String, String> maliEnv = getMaliEnvVars();
        processEnv.putAll(maliEnv);
        
        Log.i(TAG, "Applied " + maliEnv.size() + " Mali optimization env vars");
    }
}
